In [1]:

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/rjmanoj/credit-card-customer-churn-prediction/Churn_Modelling.csv

In [2]:
df = pd.read_csv("/kaggle/input/datasets/rjmanoj/credit-card-customer-churn-prediction/Churn_Modelling.csv")

In [3]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
df.shape

(10000, 14)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df['Exited'].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

In [8]:
df['Gender'].value_counts()

Gender
Male      5457
Female    4543
Name: count, dtype: int64

In [9]:
df['Geography'].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [10]:
df.drop(columns=['RowNumber', 'CustomerId','Surname'],inplace=True)

In [11]:
df = pd.get_dummies(df,columns=['Geography','Gender'],drop_first = True, dtype=int)

In [12]:
df.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,1,0,0,0
1,608,41,1,83807.86,1,0,1,112542.58,0,0,1,0
2,502,42,8,159660.80,3,1,0,113931.57,1,0,0,0
3,699,39,1,0.00,2,0,0,93826.63,0,0,0,0
4,850,43,2,125510.82,1,1,1,79084.10,0,0,1,0

In [13]:
X = df.drop(columns=['Exited'])
X.shape

(10000, 11)

In [14]:
y  = df['Exited']
y.shape

(10000,)

In [15]:
from sklearn.model_selection import train_test_split
X_train,X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state =1 )

In [16]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [17]:
X_train_scaled

array([[-0.23082038, -0.94449979, -0.70174202, ...,  1.71490137,
        -0.57273139,  0.91509065],
       [-0.25150912, -0.94449979, -0.35520275, ..., -0.58312392,
        -0.57273139, -1.09278791],
       [-0.3963303 ,  0.77498705,  0.33787579, ...,  1.71490137,
        -0.57273139, -1.09278791],
       ...,
       [ 0.22433188,  0.58393295,  1.3774936 , ..., -0.58312392,
        -0.57273139, -1.09278791],
       [ 0.13123255,  0.01077067,  1.03095433, ..., -0.58312392,
        -0.57273139, -1.09278791],
       [ 1.1656695 ,  0.29735181,  0.33787579, ...,  1.71490137,
        -0.57273139,  0.91509065]])

In [18]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [19]:
model = Sequential()

model.add(Dense(11,activation='relu',input_dim =11))
model.add(Dense(11,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
2026-07-14 10:15:47.237289: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)

In [20]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 11)             │           132 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 11)             │           132 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            12 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 276 (1.08 KB)

 Trainable params: 276 (1.08 KB)

 Non-trainable params: 0 (0.00 B)

In [21]:
 model.compile(loss='binary_crossentropy', optimizer = 'Adam',metrics =['Accuracy'],)

In [22]:
model.fit(X_train_scaled,y_train,epochs= 30, validation_split = 0.2)

Epoch 1/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - Accuracy: 0.7688 - loss: 0.5454 - val_Accuracy: 0.8012 - val_loss: 0.4782
Epoch 2/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - Accuracy: 0.8112 - loss: 0.4516 - val_Accuracy: 0.8188 - val_loss: 0.4349
Epoch 3/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - Accuracy: 0.8227 - loss: 0.4222 - val_Accuracy: 0.8275 - val_loss: 0.4153
Epoch 4/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - Accuracy: 0.8309 - loss: 0.4080 - val_Accuracy: 0.8325 - val_loss: 0.4017
Epoch 5/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - Accuracy: 0.8411 - loss: 0.3952 - val_Accuracy: 0.8406 - val_loss: 0.3887
Epoch 6/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - Accuracy: 0.8477 - loss: 0.3818 - val_Accuracy: 0.8419 - val_loss: 0.3773
Epoch 7/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - Accuracy: 0.8502 - loss: 0.3700 - val_Accuracy: 0.8469 - val_loss: 0.3654
Epoch 8/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - Accuracy: 0.8514 - loss: 0.3608 - val_Accuracy: 0.8487 - val_loss: 0.3591
Epoch 9/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - Accuracy: 0.8578 - loss: 0.3542 - val_Accuracy: 0.8481 - val_loss: 0.3548
Epoch 10/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - Accuracy: 0.8597 - loss: 0.3498 - val_Accuracy: 0.8487 - val_loss: 0.3518
Epoch 11/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - Accuracy: 0.8608 - loss: 0.3460 - val_Accuracy: 0.8506 - val_loss: 0.3489
Epoch 12/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - Accuracy: 0.8612 - loss: 0.3443 - val_Accuracy: 0.8519 - val_loss: 0.3474
Epoch 13/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - Accuracy: 0.8602 - loss: 0.3428 - val_Accuracy: 0.8525 - val_loss: 0.3462
Epoch 14/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - Accuracy: 0.8619 - loss: 0.3416 - val_Accuracy: 0.8481 - val_loss: 0.3467
Epoch 15/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - Accuracy: 0.8603 - loss: 0.3404 - val_Accuracy: 0.8512 - val_loss: 0.3450
Epoch 16/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - Accuracy: 0.8625 - loss: 0.3396 - val_Accuracy: 0.8531 - val_loss: 0.3443
Epoch 17/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - Accuracy: 0.8630 - loss: 0.3385 - val_Accuracy: 0.8487 - val_loss: 0.3453
Epoch 18/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - Accuracy: 0.8636 - loss: 0.3383 - val_Accuracy: 0.8494 - val_loss: 0.3446
Epoch 19/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - Accuracy: 0.8628 - loss: 0.3372 - val_Accuracy: 0.8506 - val_loss: 0.3437
Epoch 20/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - Accuracy: 0.8622 - loss: 0.3366 - val_Accuracy: 0.8544 - val_loss: 0.3443
Epoch 21/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - Accuracy: 0.8631 - loss: 0.3369 - val_Accuracy: 0.8525 - val_loss: 0.3436
Epoch 22/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - Accuracy: 0.8619 - loss: 0.3358 - val_Accuracy: 0.8487 - val_loss: 0.3447
Epoch 23/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - Accuracy: 0.8628 - loss: 0.3352 - val_Accuracy: 0.8519 - val_loss: 0.3438
Epoch 24/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - Accuracy: 0.8623 - loss: 0.3353 - val_Accuracy: 0.8487 - val_loss: 0.3453
Epoch 25/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - Accuracy: 0.8641 - loss: 0.3350 - val_Accuracy: 0.8481 - val_loss: 0.3449
Epoch 26/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - Accuracy: 0.8633 - loss: 0.3343 - val_Accuracy: 0.8494 - val_loss: 0.3447
Epoch 27/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - Accuracy: 0.8647 - loss: 0.3336 - val_Accuracy: 0.8531 - val_loss: 0.3434
Epoch 28/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - Accuracy: 0.8631 - loss: 0.3336 - val_Accuracy: 0.8475 - val_loss: 0.3454
Epoch 29/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - Accuracy: 0.8625 - loss: 0.3327 - val_Accuracy: 0.8469 - val_loss: 0.3454
Epoch 30/30
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - Accuracy: 0.8628 - loss: 0.3333 - val_Accuracy: 0.8494 - val_loss: 0.3448

In [23]:
model.layers[0].get_weights()

[array([[ 3.65795016e-01, -2.48902496e-02, -2.87309609e-04,
          2.55982429e-01,  1.04588695e-01,  2.29941577e-01,
          3.33059639e-01,  2.76728153e-01, -2.93754756e-01,
         -4.44323719e-02, -2.04754412e-01],
        [-7.15584606e-02,  8.09751570e-01,  1.21847764e-01,
          3.14834774e-01,  3.35381538e-01,  1.76498055e-01,
          3.53833705e-01, -1.02298759e-01, -2.62886226e-01,
          1.01481509e+00, -4.28441823e-01],
        [-2.98034221e-01, -2.68547479e-02, -2.64061272e-01,
         -1.16092734e-01,  4.16630477e-01,  9.25576910e-02,
          8.14393163e-02, -5.47613025e-01,  4.80508834e-01,
         -8.18593130e-02,  8.37302133e-02],
        [-5.76792695e-02, -5.18203199e-01, -1.34725451e-01,
          3.56894284e-01,  3.07435244e-01,  4.63914126e-01,
          4.33758944e-02, -3.82429749e-01, -4.35533077e-01,
          7.69428583e-03, -1.62361696e-01],
        [ 8.46811384e-02, -9.75375831e-01,  3.23862225e-01,
         -1.60180926e-01, -7.54674450e-02,  9.37681377e-01,
         -1.82495967e-01,  4.59228814e-01,  2.09550355e-02,
          9.06779110e-01,  2.56266743e-01],
        [-2.26587858e-02, -6.25398979e-02,  1.10218756e-01,
          6.47915825e-02, -1.34972170e-01, -1.09430075e-01,
          3.97342056e-01, -2.81446371e-02, -4.62618582e-02,
          7.89915025e-02,  3.24515730e-01],
        [-7.91983977e-02, -1.22840628e-01, -5.94268322e-01,
         -1.06554937e+00,  3.91692072e-01, -3.37655962e-01,
          6.14976346e-01, -1.77614808e-01, -3.52912694e-01,
          1.38370395e-01,  5.00895321e-01],
        [ 2.81721324e-01, -2.56251469e-02,  1.63427964e-01,
          9.04303491e-02,  7.83666000e-02,  6.41313493e-02,
          2.94962496e-01,  1.93230752e-02, -3.07844907e-01,
         -1.19753763e-01, -2.82848567e-01],
        [-2.56798174e-02,  3.30831528e-01,  2.23314986e-01,
          4.12924618e-01, -2.40848646e-01, -1.83817685e-01,
         -3.22510898e-01,  2.47666985e-01,  1.63486481e-01,
          1.88504055e-01, -4.02854830e-01],
        [-3.15054834e-01,  4.63948473e-02,  1.06385559e-01,
         -9.03048292e-02,  4.20806482e-02,  1.67131960e-01,
          2.46464968e-01,  3.90200727e-02,  3.39271575e-01,
          1.05339967e-01, -1.22101836e-01],
        [ 6.75882578e-01,  1.07246622e-01,  6.66316524e-02,
          5.81487641e-02,  1.48813412e-01, -5.10159358e-02,
          3.14001963e-02, -8.27047229e-02,  4.04747754e-01,
          1.53708160e-01, -1.82277411e-01]], dtype=float32),
 array([ 0.5241712 ,  0.17343958, -0.3022365 ,  0.33687344,  0.04589439,
        -0.28277788, -0.13598667,  0.55053127,  0.711655  , -0.34317967,
         0.05629428], dtype=float32)]

In [24]:
y_log = model.predict(X_test_scaled)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

In [25]:
y_pred=np.where(y_log>0.5,1,0)

In [26]:
y_pred

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [27]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.861